### ISSUE TITLE
Question: Multi-tenancy support

### ISSUE THREAD

**Issue by AsimNet** [ever-co/ever#1008]
Hello,
 thank you for the excellent work...
if I want to support multiple sites, what should I do? or add
is intercepting HTTP calls is enough (adding X-tenant variable in headers payload) and then adding a new entity wrap everything to each shop?
I don't know what's the best way to do it, could you please guide me, also I'm wondering is there a flow-chart or proper documentation? that could help also...

thank you again

**Comment by evereq** [comment]
Hi @AsimNet, 

1) What do you mean exactly by support multiple sites? The platform provides code for one site or mobile app which works for single store or as a marketplace, where products available from multiple stores. If you want to have another website that shows **same** products, you just need to setup it and make sure it connects to the same API as the first site. So you can, in theory, have 100s of sites working on different domains, each shows the same products from different (or single) merchants.

2) It also should be possible I think to filter products by single store (warehouseId) and so that way to make sure your mobile app or webshop always shows products from only a specific store. That's needed/used when you want to provide each store/merchant with own branded web / mobile app!

3) So while platform support Marketplace mode (multi-store), only our SaaS version will support the concept of multiple tenants because you don't really need that, unless you want to allow multiple organizations to use our platform to build OWN (different!) Marketplaces online. E.g. say mode when you have mysuperplatform.co website and on it, people can register and create OWN marketplaces like marketA.mysuperplatform.co, marketB.mysuperplatform.co and so on. That's an advanced multi-tenant scenario that only our SaaS will support. However, if you want to do something like that, you can create a script that will provision platform API and apps on different domains (ports) on one or more servers and that way you will have the ability to create marketplaces for different clients, etc. In most cases, users of our platform want to just build one specific marketplace (web or mobile app) or even one specific web shop or mobile app with on-demand deliveries. Let me know if your scenario is something different, I will try to provide more details.

4) Unfortunately, we do not have good docs yet, but if you have more questions we will be more than happy to answer here (or Slack / Discord etc, see Contact Us at https://github.com/ever-co/ever#contact-us

**Comment by AsimNet** [comment]
thank you @evereq 
what I'm looking for is a marketplace (multiple independent shops with a unified carrier platform or with a third-party provider)
ever platform solves this problem...
for now, I'm trying to install the project on my machine, to get familiar with and to I'll be happy to help

thank you guys
