### ISSUE TITLE
During checkout, upon entering delivery address, the address is not recognized

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1022]
Step by step:

![image](https://user-images.githubusercontent.com/59708947/76082222-9bf67500-5f89-11ea-9f10-256a03b0f8a2.png)

![image](https://user-images.githubusercontent.com/59708947/76085561-0959d400-5f91-11ea-9f11-149a2b5c0a66.png)

It doesn't recognize de address, it delivers to the default location of the mobile shop module:

![image](https://user-images.githubusercontent.com/59708947/76085758-6f465b80-5f91-11ea-88e0-92f2ce32a52f.png)

The entered address is here:

![image](https://user-images.githubusercontent.com/59708947/76085837-8edd8400-5f91-11ea-8f5b-ffa0c9605ff8.png)

I've cleaned all caches and cookies, done with other Internet browser and with incognito windows, and still the same.

**Comment by morggansoft** [comment]
Hi @AlishMekliov931, we are verifying but the issue still persists

**Comment by morggansoft** [comment]
It's now solved. Thanks.

**Comment by AlishMekliov931** [comment]
The follow logic is did to fix this bug:
In Test environment (when default coordinates in env file are NOT null) are used default coordinates to auto fill the user address. If the user change this address and Google API detect full data (city, street, str. number), then will be used the coordinates form the address which user changed, otherwise if user type some wrong address will be used default coordinates.
In Production environment (when default coordinates in env file are null) is same logic as in Test environment but instead the default coordinates, are used coordinates from GPS.
CC: @evereq @morggansoft
