### ISSUE TITLE
Merchant: history orders not showing date

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1055]
On Merchant, history orders not showing the creation date of there.

![Merchant en el historico de pedidos no se muestra fecha de la orden](https://user-images.githubusercontent.com/59708947/78198989-c5a79c80-7460-11ea-9f39-6aae86e01849.png)

**Comment by evereq** [comment]
Note: it's by design this way. 

Idea is that there are lots of orders daily for on-demand business and it's the time of order is what important, not the date in case of orders processed on-demand (e.g. same day or same hour delivery). 

Btw, think the date actually can be seen at the left top corner near order number (18/3 on the screenshot above).
