### ISSUE TITLE
On merchant App track carrier search doesn't work properly

### ISSUE THREAD

**Issue by sunk0** [ever-co/ever#1229]
https://www.loom.com/share/fad5b001a4f44d1b866cdb81f9dff279

**Comment by evereq** [comment]
@valiopld please see code https://github.com/ever-co/ever/pull/1261/files, but from what I understand it did not solve all issues... try to solve that puzzle, please :)

**Comment by valiopld** [comment]
@evereq
I think its better to rebuild the whole component because its a little bit a mess inside.
If you agree,
I am a little bit confusing what exactly means "Total Carriers", "Total Deliveries " ... maybe TOTAL carriers registered in the app?
 
If you want just to fix the problem with the changing carrier from the dropdown 
- do you want to add a button "clear" for cleaning the search carrier filter?

**Comment by evereq** [comment]
@valiopld lets not rebuild something before you understand it all... lets chat about it next week. Total carriers, total deliveries, total active carriers are self explained, no? How many carriers merchant have totally, how many are active right now, how many deliveries they did etc.
