### ISSUE TITLE
On Admin panel when creating order from store available checkbox not working

### ISSUE THREAD

**Issue by sunk0** [ever-co/ever#1243]
https://www.loom.com/share/e3728fd26d4340e6bff93d288ff9416c

**Comment by YavorGrancharov** [comment]
Here, when creating new order, the checkbox for showing only available products doesn't seem to set some property to database but just filters products with zero quantity as can be seen on provided video preview below. I wander if we set product to zero manually or when product reaches zero because it is ordered given amount of times, should we set Availability checkbox inside products panel to false automatically?
https://www.loom.com/share/efdd1a5125d64a5dbdb7a730ffa97a5e

**Comment by evereq** [comment]
@YavorGrancharov let's keep "availability" value in DB (true / false) separate from available product count. I.e. some merchant may still want to SHOW products they have, even if they don't have them in Stock, for example for users to pre-order them etc. 
So to answer your question: "I wander if we set product to zero manually or when product reaches zero because it is ordered given amount of times, should we set Availability checkbox inside products panel to false automatically?" answer is NO.

However, I don't understand why you asking that if the actual issue was about the different use cases. Products count was set to 97, but product availability was set to "false". In such case, we absolutely should NOT show such products anywhere! I.e. let me repeat it: if product availability set to "false", such products should be hidden in all customer-related apps (shop website and show mobile app). At the same, if product availability set to "true", in some cases (later, not now!) we MAY actually display such products to customers, even if qty of products is 0 (as I said, will be pre-order feature later).

So what you should do now? Make sure that in both stores, if "availability" is false, we do NOT display products for purchase. Do NOT touch existed logic related to count of products because it will be much improved in the future (with unlimited products or with pre-orders etc), it's really complex and not right now.
