### ISSUE TITLE
On Admin panel when updating store to Inactive not showing orders

### ISSUE THREAD

**Issue by sunk0** [ever-co/ever#1244]
https://www.loom.com/share/41f180de185640998f417b37700af3d6

**Comment by evereq** [comment]
@YavorGrancharov we need to do more research. When the store set not active in Admin, customers should not see products/orders, etc from such a store. However, in Admin, I am not sure. If we use "Active" as "delete", then I think in Admin it should also not be visible anymore (considered deleted). But according to video, it seems like in some places we still show it, even if it set not active. Do we have a separate field for "isDeleted" or something like that? Please research and let me know

**Comment by YavorGrancharov** [comment]
@evereq Yes, there is isDeleted filed in warehouse data
![Inked9RuPpMSE3j_LI](https://user-images.githubusercontent.com/28997304/87916256-ddd91100-ca7b-11ea-8047-b8f9718cc727.jpg)

**Comment by evereq** [comment]
@YavorGrancharov ok, so if there is "isDeleted" field than logic should be simple:
- if "isDeleted" set to true, such Merchant / Orders should NOT appear anywhere, including Admin UI
- if "isActive" set to false, such Merchant / Orders should STILL appear in the Admin UI because Admin may want to set such merchant Active at any time, edit details or see past orders, etc. I.e. this ticket is a BUG and should be fixed for Admin! 

Note: in the customer webshop/customer ordering mobile app, of course, if merchant "isActive" set to false, we should NOT show products from such merchants! However, we should still show orders in the "Orders History" pages! Because even if tomorrow the merchant become not active, the customer may still want to see her/his past orders!

Please let me know if you have any questions.

**Comment by YavorGrancharov** [comment]
Fixed
https://www.loom.com/share/3e22677a8e004fd2aa6223365aa40847
