### ISSUE TITLE
Mobile shop app don't show products when changing language

### ISSUE THREAD

**Issue by sunk0** [ever-co/ever#1282]
https://www.loom.com/share/4a2ee237ba7f46bbacef1b65f93e6398

**Comment by YavorGrancharov** [comment]
It is actually working just fine because every product has locale property connected with certain language and image, if we add images to all languages then on change language we will be seeing the corresponding image for the same product!
![NqRP3ZiPZM](https://user-images.githubusercontent.com/28997304/88528116-e050e300-d006-11ea-9974-80f80983fe5a.png)

https://www.loom.com/share/9401e6f381bc4b6f94e72c33eb16c103

**Comment by sunk0** [comment]
![language problem](https://user-images.githubusercontent.com/36041324/88528631-8b619c80-d007-11ea-9c78-ff6ca20fbe23.PNG)

**Comment by sunk0** [comment]
Don't works for me
