### ISSUE TITLE
Cannot use namespace on running yarn run:shopweb

### ISSUE THREAD

**Issue by saurabh1223** [ever-co/ever#813]
[ever_error_website_port_3000.txt](https://github.com/ever-co/ever/files/3522360/ever_error_website_port_3000.txt)

Please find logs while running yarn run:shopweb

**Comment by evereq** [comment]
@saurabh1223 can't tell what exactly cause such issues, most probably incorrect version of TypeScript or again issues with symlinks... 
Please see https://circleci.com/gh/ever-co/ever/tree/develop, it's our continues build and as you see all last builds are green. 

More specifically, see https://circleci.com/gh/ever-co/ever/18179 

I refer you to our continues build system because you can digg inside to see how to make build working, what Docker image/node version it uses, etc.
