### ISSUE TITLE
Property 'redirectUrl' does not exist on type 'User'.

### ISSUE THREAD

**Issue by rmros** [ever-co/ever#843]
---> 1bdd6c6df0f3
Step 12/22 : COPY yarn.lock /tmp/yarn.lock
 ---> Using cache
 ---> c4ee4fd11bf8
Step 13/22 : RUN cd /tmp/ && yarn install
 ---> Using cache
 ---> b005ff3d86d4
Step 14/22 : RUN cp -a /tmp/node_modules /usr/src/app/
 ---> Using cache
 ---> e637fa959cde
Step 15/22 : RUN cd /usr/src/app
 ---> Using cache
 ---> 0edbca6b44f7
Step 16/22 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 91b2da8388b4
Step 17/22 : ADD . /usr/src/app
 ---> 6e84d2c48201
Step 18/22 : RUN $(npm bin)/tsc
 ---> Running in 1b0448a136a0
src/services/services.app.ts(622,45): error TS2339: Property 'redirectUrl' does not exist on type 'User'.
src/services/services.app.ts(651,45): error TS2339: Property 'redirectUrl' does not exist on type 'User'.
ERROR: Service 'api' failed to build: The command '/bin/sh -c $(npm bin)/tsc' returned a non-zero code: 2

**Comment by evereq** [comment]
@rmros from the output above, are you attempting to run it in the docker? Our Docker files are not working yet, sorry, you will need to manually install it all on your target PC (unless you create your own dockerfile and in such case please share it with us). The problem with Docker is issues with symlinks we are using to reference shared modules (however for some reason your issue seems to be different).
