### ISSUE TITLE
customization or sponsorship

### ISSUE THREAD

**Issue by WimpyMistake** [ever-co/ever#945]
Hello guys,
This looks like a nice work. Will try it out soon.
Our company is looking for a solution with similar tech stack and functionalities like yours. Do you accept customization requests? Or willing to accept sponsorship for this framework?

**Comment by evereq** [comment]
Hey, @WimpyMistake glad you like our work, thank you for the feedback! 👍 

Yes, we accept customization requests or even requests to build similar (or different) software from the beginning. We are running our own development agency 💃  

Now, because the licensing is relevant for any changes/usage of open-source software, I should point out that our platform is dual licensed (AGPL v3 and Enterprise license) and so for every customization request the main question would be: can you keep customization changes (source code changes) public and under the same license we are using or not. For example, if it's fine for your business to make a public fork of repo and do required changes and keep it all public under AGPL v3, you don't need to purchase a separate license from us and all good changes will contribute for our community. You can hire us (or someone else) to do all such changes at any moment. At the same time, for some businesses, it's better to keep changes private and they need to buy Enterprise license to be able to do so. Note: The above is not legal advice, just a point to research / decide on licensing for your specific business case because it's important. You can find a bit more details about licensing at https://github.com/ever-co/ever/blob/develop/LICENSE.md. Let me know if you have any questions about that, I would be glad to help/provide more info about that topic. 

Regarding sponsorship, at the moment we do not accept it, but as I said above you can hire our company to do customization (and/or other) services and that way you will basically provide us with revenue to support future development.
Feel free to drop us email to ever@ever.co and describe what customizations you need and we will give you more details about costs, timeline, etc (we are working on per hour bases only and our R&D in Bulgaria, so costs are 💯more than affordable)

**Comment by evereq** [comment]
@WimpyMistake one more thing: we have this repo https://github.com/ever-co/feature-requests/issues for futures requests, so as long as you think they may give some benefits for the community, feel free to add your requests there. If we will see that some feature requests aligned with our vision/roadmaps, we can implement them without a need for any additional payments from your side :) Our platform is still in the development phase, so any of such requests/feedback more than welcome!!!

**Comment by WimpyMistake** [comment]
@evereq Thank you so much for the detailed explanation! I'm glad to hear the good news. Yeah we might go for the enterprise license. I will be emailing ever@ever.co shortly with further info and questions.

**Comment by WimpyMistake** [comment]
Hi @evereq just to confirm if you have received my emails? Thanks!

**Comment by evereq** [comment]
@WimpyMistake hey, yes we got an email, sorry for the delay, I will reply soon.
Meanwhile, you can see https://www.screencast.com/users/evereq/folders/Snagit/media/b70568ee-c081-40e2-9208-52a358948666, it's some additional demo of our platform for Massage ordering app (it gives a good overview of amount of features in the platform ordering app today).
