### ISSUE TITLE
GraphQL server failing to start due to exception

### ISSUE THREAD

**Issue by bot101** [ever-co/ever#969]
Successfully setup the project but I couldn't get the GraphQL server to start as all requests to `localhost:5555` is refused. I got the error message below whenever I execute `yarn run:server`
```
Uncaught rejection: Error: Unable to merge GraphQL type
 "Mutation": Field "updateEmail" already defined with a different
type. Declared as "Carrier", but you tried to override with "User"
```

**Comment by evereq** [comment]
@bot101 yep, we saw such errors before when we upgrade to the new structure in https://github.com/ever-co/ever/tree/feature/use-packages branch (which involves updating of lots of packages and support of latest NodeJS). However, we never faced it with `develop` or `master` branch code before...  The reason for such error could be because we have same mutation "updateEmail" defined in 2 places:
- https://github.com/ever-co/ever/blob/develop/backend/api/src/graphql/carriers/carriers.types.graphql#L115
- https://github.com/ever-co/ever/blob/develop/backend/api/src/graphql/users/users.types.graphql#L138

The simplest way to solve it is to just rename mutations (and resolvers) to different names :) 
I did it at https://github.com/ever-co/ever/tree/fix/graphql-duplicate-mutation-names branch and merged to `develop`, so you can just pull latest from `develop` and try to run it again.

Let me know if it helps, not sure if you will not get other errors after that fix, because it looks like something different in your env compared to others we tested...
