### ISSUE TITLE
Carrier App - Distance to Client's House

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#984]
The distance to the client's house is always the same, it does not change when changing the delivery address

![IMG_7585](https://user-images.githubusercontent.com/59708947/72932408-84975b80-3d3e-11ea-8b6f-903cbf7a7e09.jpg)

![IMG_7584](https://user-images.githubusercontent.com/59708947/72932420-88c37900-3d3e-11ea-8db8-b6886d5e878b.jpg)

**Comment by evereq** [comment]
@AlishMekliov931 please check if we implemented that feature or it's a bug and let us know

**Comment by AlishMekliov931** [comment]
@morggansoft As the base functionality depends on coordinates, i.e customer will see products only near him (around 5km), also and the carrier see orders for delivering only near him (around 5km), we decided for testing to use a default (fixed) coordinates so can test easily all functionality. Otherwise, you have to create manually the Merchant, Customer, and Carriers with close coordinates and set empty values on settings DEFAULT_LATITUDE and DEFAULT_LONGITUDE for all angular apps (carrier, shop web etc.)
cc: @evereq

**Comment by morggansoft** [comment]
Ok Alish, we will then test with real data, to be able to test the functionality well.
