### ISSUE TITLE
Carrier App -  Cancel Order

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#985]
When you want to cancel an order taken, (for example because the customer was not there), clicking Cancel does not work correctly (you should return to the Take Orders screen)

**Comment by AlishMekliov931** [comment]
@morggansoft The logic for canceling an order from the carrier is following:
1. When a carrier is taking the order from the merchant, but before he starts to deliver, decide to cancel it, is shown a page with buttons Return Product and Cancel.
1.1. Return Product - complete returning the order, so another carrier can take it
1.2. Cancel - Continue to deliver the order
https://www.screencast.com/t/7e9J1oX9kP

2. When a carrier is already started to delivering, decide to cancel (because the customer was not there, or by mistake) it
is shown a page with buttons I'm there and Cancel.
1.1. I'm there - will show a page only with one button Return Product which will complete returning the order.
1.2. Cancel (if the carrier is pressed in 2. by mistake or another reason which allow him to continue) - Continue to deliver the order
https://www.screencast.com/t/JX3fGr1kL

CC: @evereq

**Comment by morggansoft** [comment]
Ok Alish, great. We test these functionalities in this way.
