### ISSUE TITLE
Merchant App: Given to Carrier Status on dashboard screen

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#987]
An order in given to carrier status does not disappear from the order dashboard when that status is designated

**Comment by morggansoft** [comment]
![merchant](https://user-images.githubusercontent.com/59708947/73041729-4b91e080-3e3d-11ea-8461-88bf999574f1.png)

**Comment by AlishMekliov931** [comment]
@morggansoft The order from your screenshot has status "Packaged" (the status is shown in the top right corner of the order box). The button "Given to Carrier" is disabled because the order is not picketed up form Carrier. Once some carrier picket it up the button will be enabled and order moved from the relevant order dashboard. See a video about how to simulate the flow https://www.screencast.com/t/d2e6FikJOJ
CC: @evereq

**Comment by morggansoft** [comment]
Ok Alish. We will test the functionality with a complete order cycle again. We had done it, but the orders did not appear on the Carrier's screen so he would take them. We will test with "clean" data again.
